version: '3'

services:
  react-app:
    build:
      context: ./pyramidfront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["serve", "-s", "build"]
    volumes:
      - ./pyramidfront:/app

  django-app:
    build:
      context: ./pyramidspharmacy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./pyramidspharmacy:/app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

volumes:
  postgres_data:

