version: '3'

services:
  react-app:
    build:
      context: ./pyramidfront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["serve", "-s", "build"]
    volumes:
      - ./pyramidfront:/app

  django-app:
    build:
      context: ./pyramidspharmacy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./pyramidspharmacy:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:

