# Generated by Django 4.2.16 on 2024-11-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicationapp', '0003_refillrequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
